spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      eclipselink:
        weaving: static
        generate-ddl: none
        logging.level: FINEST
        logging.logger: DefaultLogger
        logging.level.sql: FINER
        logging.parameters: true
        jdbc.allow-native-sql-queries: true
        jdbc.uppercase-columns: true
        cache.shared.default: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=test
    username: postgres
    password: postgres

server:
  port: 8080
  max-http-header-size: 16384